DEFAULT_SETTINGS = {
    "target_roles": [
        "RTL Design Engineer",
        "Physical Design Engineer",
        "Design Verification Engineer",
        "ASIC Design Engineer",
        "Digital Design Engineer",
        "RTL Intern",
        "Physical Design Intern",
        "Design Verification Intern",
        "VLSI Intern",
        "ASIC Design Manager",
        "RTL Lead",
        "Verification Lead",
        "Physical Design Lead",
        "VLSI Manager",
        "Hiring Manager",
        "Engineering Manager",
        "Technical Lead",
        "Technical Recruiter",
    ],
    "target_technical_skills": [
        "RTL Design",
        "Physical Design",
        "Design Verification",
        "VLSI",
        "ASIC",
        "RTL",
        "Digital Design",
        "Verilog",
        "SystemVerilog",
        "SoC",
        "FPGA",
        "UVM",
        "STA",
        "Synthesis",
        "ASIC Verification",
        "Functional Verification",
        "Place and Route",
        "Timing Closure",
    ],
    "target_locations": [
        "Ahmedabad",
        "Gujarat",
        "Bangalore",
        "Noida",
        "Hyderabad",
    ],
    "target_companies": [
        "Skychip",
        "Quest Global",
        "ASICCraft",
        "Pronesis",
        "KeenSemi",
        "PravegSemi",
        "Exemitas Design",
        "VeerVX",
        "MosChip",
        "Truechip",
        "Verifast",
        "Vicharak",
        "MumbaiSemi",
        "proteanTecs",
        "Incise Infotech",
        "Cyient Semiconductors",
        "Chip Smart Technologies",
        "AumRaj Design Systems",
        "Mirafra",
        "INDSEMI TECH",
        "PulseWave Semiconductor",
        "SmartSoC Solutions",
        "RRP Electronics",
        "CG Semi",
        "Nordic Semiconductor",
        "indie Semiconductor / IndieSemi",
        "ScaleEdge Technology",
        "Renesas Electronics",
        "SuchiLogic",
        "Suchi Semicon",
        "Kaynes Semicon",
        "Insemi Technology Services",
        "Blueberry Semiconductors",
        "SignOff Semiconductors",
        "TRISEMI TECHNOLOGIES",
        "Radiant Semiconductors",
        "Digicomm Semiconductor",
        "NetraSemi",
        "Trident Techlabs",
        "eInfochips",
        "Green Semiconductors",
        "SK hynix",
        "Marvell Technology",
        "Rambus",
        "Sankalp Semiconductor",
        "Cypress Semiconductor",
    ],
    "priority_companies": [
        "NVIDIA",
        "Tessolve",
        "MediaTek",
        "SanDisk",
        "Micron",
        "Synopsys",
        "Infineon",
        "NXP",
        "Qualcomm",
        "NXP India",
        "Intel",
        "Google",
        "Arm",
        "AMD",
        "Texas Instruments",
        "Altera",
        "Cisco",
        "Nokia",
        "IBM",
    ],
    "daily_lead_target": 15,
    "min_relevance_score": 60.0,
    "candidate_profile": {
        "name": "Aarav Patel (Candidate Profile)",
        "education": "B.Tech / M.Tech in Electronics & Communication Engineering (ECE)",
        "focus": "VLSI / ASIC Design / Digital Design / AI Hardware Acceleration",
        "skills": [
            "Verilog",
            "SystemVerilog",
            "AMBA APB / AXI",
            "RISC-V Architecture",
            "RTL Design & Synthesis",
            "OpenLane RTL-to-GDS Flow",
            "C/C++",
            "Python",
            "Linux / Bash",
            "Static Timing Analysis (STA)",
            "ModelSim / QuestaSim",
            "Yosys / OpenSTA",
        ],
        "projects": [
            {
                "name": "AMBA APB Protocol Bridge & Verification",
                "description": "Designed synthesis-ready AMBA 3 APB Master/Slave interface with comprehensive SystemVerilog testbench, assertions, and coverage.",
                "technologies": ["Verilog", "SystemVerilog", "AMBA APB", "QuestaSim"],
            },
            {
                "name": "RISC-V 32I Pipelined Core & Cache Analysis",
                "description": "Implemented 5-stage pipelined RV32I processor with hazard detection, forwarding unit, and configurable direct-mapped L1 instruction/data cache.",
                "technologies": ["SystemVerilog", "Computer Architecture", "Cache Design", "GTKWave"],
            },
            {
                "name": "UART Controller with FIFO (RTL to GDSII Flow)",
                "description": "Completed full RTL-to-GDS flow on SkyWater 130nm node using OpenLane, achieving zero DRC/LVS violations with timing closure at 100MHz.",
                "technologies": ["Verilog", "OpenLane", "SkyWater 130nm", "Yosys", "OpenSTA"],
            },
        ],
        "experience": "Fresher / Entry-Level Hardware Engineer with strong academic & project portfolio in RTL Design, Verification & Digital VLSI.",
        "resumeUrl": "https://example.com/aarav-patel-vlsi-resume.pdf",
        "portfolioUrl": "https://github.com/example/aarav-patel-hardware",
        "email": "aarav.patel.vlsi@example.com",
    },
    "last_daily_generation_date": "2026-08-16",
}

DEFAULT_COMPANIES = [
    {
        "name": "AMD",
        "industry": "Semiconductors & High-Performance Computing",
        "location": "Bangalore / Hyderabad, India",
        "website_url": "https://www.amd.com",
        "linkedin_url": "https://www.linkedin.com/company/amd",
        "tech_focus": ["ASIC", "RTL", "SoC", "VLSI", "Computer Architecture", "AI Hardware"],
        "description": "Leading innovator in high-performance GPU, CPU, and custom adaptive computing SoC architectures.",
        "last_researched": "2026-08-15",
        "tier": "Tier 1",
        "is_saved": True,
    },
    {
        "name": "Qualcomm",
        "industry": "Wireless & Mobile Silicon Technologies",
        "location": "Bangalore / Hyderabad / Chennai, India",
        "website_url": "https://www.qualcomm.com",
        "linkedin_url": "https://www.linkedin.com/company/qualcomm",
        "tech_focus": ["SoC", "RTL", "VLSI", "Design Verification", "SystemVerilog", "Physical Design"],
        "description": "Pioneer in Snapdragon mobile processors, modem DSPs, and next-generation automotive compute.",
        "last_researched": "2026-08-14",
        "tier": "Tier 1",
        "is_saved": True,
    },
    {
        "name": "NVIDIA",
        "industry": "AI Hardware & GPU Accelerated Computing",
        "location": "Bangalore / Pune / Hyderabad, India",
        "website_url": "https://www.nvidia.com",
        "linkedin_url": "https://www.linkedin.com/company/nvidia",
        "tech_focus": ["AI Hardware", "ASIC", "VLSI", "RTL", "Design Verification", "Physical Design"],
        "description": "Global leader in GPU architecture, Tensor Core AI hardware engines, and high-speed interconnect fabric.",
        "last_researched": "2026-08-16",
        "tier": "Tier 1",
        "is_saved": True,
    },
    {
        "name": "Intel Corporation",
        "industry": "Semiconductors & Silicon Architecture",
        "location": "Bangalore, India",
        "website_url": "https://www.intel.com",
        "linkedin_url": "https://www.linkedin.com/company/intel-corporation",
        "tech_focus": ["ASIC", "SoC", "Computer Architecture", "Physical Design", "Verilog", "VLSI"],
        "description": "World-renowned semiconductor manufacturer developing client, data-center CPUs, and foundry services.",
        "last_researched": "2026-08-12",
        "tier": "Tier 1",
        "is_saved": True,
    },
    {
        "name": "Synopsys",
        "industry": "Electronic Design Automation (EDA) & Semiconductor IP",
        "location": "Bangalore / Hyderabad / Noida, India",
        "website_url": "https://www.synopsys.com",
        "linkedin_url": "https://www.linkedin.com/company/synopsys-inc",
        "tech_focus": ["EDA", "VLSI", "ASIC", "Design Verification", "Physical Design", "SystemVerilog"],
        "description": "Premier EDA tools and silicon design IP provider empowering advanced SoC development worldwide.",
        "last_researched": "2026-08-10",
        "tier": "Tier 1",
        "is_saved": False,
    },
    {
        "name": "Cadence Design Systems",
        "industry": "Electronic Design Automation & Silicon Engineering",
        "location": "Bangalore / Noida / Pune, India",
        "website_url": "https://www.cadence.com",
        "linkedin_url": "https://www.linkedin.com/company/cadence-design-systems",
        "tech_focus": ["EDA", "Physical Design", "VLSI", "Design Verification", "SoC"],
        "description": "Key provider of EDA software, emulation hardware, and IP solutions for digital and custom ICs.",
        "last_researched": "2026-08-11",
        "tier": "Tier 1",
        "is_saved": False,
    },
    {
        "name": "Texas Instruments",
        "industry": "Analog & Embedded Processing Semiconductors",
        "location": "Bangalore, India",
        "website_url": "https://www.ti.com",
        "linkedin_url": "https://www.linkedin.com/company/texas-instruments",
        "tech_focus": ["VLSI", "ASIC", "SoC", "Verilog", "Physical Design"],
        "description": "Global semiconductor company designing analog ICs and embedded processors for industrial and automotive markets.",
        "last_researched": "2026-08-13",
        "tier": "Tier 1",
        "is_saved": True,
    },
    {
        "name": "ARM",
        "industry": "Processor IP & Semiconductor Architecture",
        "location": "Bangalore / Noida, India",
        "website_url": "https://www.arm.com",
        "linkedin_url": "https://www.linkedin.com/company/arm",
        "tech_focus": ["RISC-V", "Computer Architecture", "RTL", "ASIC", "SystemVerilog", "VLSI"],
        "description": "Pioneer of energy-efficient processor IP cores, interconnect fabrics, and micro-architecture architectures.",
        "last_researched": "2026-08-09",
        "tier": "Tier 1",
        "is_saved": True,
    },
    {
        "name": "MediaTek",
        "industry": "Fabless Semiconductor & Wireless SoCs",
        "location": "Bangalore / Noida, India",
        "website_url": "https://www.mediatek.com",
        "linkedin_url": "https://www.linkedin.com/company/mediatek",
        "tech_focus": ["SoC", "RTL", "VLSI", "ASIC", "Design Verification"],
        "description": "Leading fabless semiconductor company powering smart devices, IoT, and high-performance Dimensity chipsets.",
        "last_researched": "2026-08-08",
        "tier": "Tier 2",
        "is_saved": False,
    },
    {
        "name": "Western Digital",
        "industry": "Data Storage Silicon & Flash Memory Controllers",
        "location": "Bangalore, India",
        "website_url": "https://www.westerndigital.com",
        "linkedin_url": "https://www.linkedin.com/company/western-digital",
        "tech_focus": ["ASIC", "RISC-V", "RTL", "Design Verification", "VLSI"],
        "description": "Leading flash storage developer creating in-house RISC-V based storage controller ASICs.",
        "last_researched": "2026-08-07",
        "tier": "Tier 2",
        "is_saved": False,
    },
]

DEFAULT_JOBS = [
    {
        "title": "RTL Design Engineer — ASIC / SoC Subsystems",
        "company": "AMD",
        "location": "Bangalore, India",
        "url": "https://example.com/careers/amd-rtl-design-engineer",
        "description": "We are looking for an ambitious RTL Engineer with strong proficiency in Verilog / SystemVerilog to design high-speed bus interfaces, AMBA APB/AXI peripherals, and power-aware logic for next-generation compute engines.",
        "required_skills": ["Verilog", "SystemVerilog", "RTL", "AMBA APB", "STA", "Linting"],
        "date_discovered": "2026-08-15",
        "status": "SAVED",
        "salary_range": "₹14L - ₹22L PA",
        "experience_level": "0-3 Years",
        "associated_contact_ids": [],
    },
    {
        "title": "ASIC Verification Engineer (UVM / SystemVerilog)",
        "company": "Qualcomm",
        "location": "Hyderabad, India",
        "url": "https://example.com/careers/qualcomm-asic-verification",
        "description": "Seeking Design Verification engineers to build constrained random testbenches, assertions (SVA), and functional coverage plans for 5G modem subsystem blocks.",
        "required_skills": ["SystemVerilog", "UVM", "Design Verification", "Verilog", "Coverage"],
        "date_discovered": "2026-08-14",
        "status": "NEW",
        "salary_range": "₹15L - ₹24L PA",
        "experience_level": "1-3 Years",
        "associated_contact_ids": [],
    },
    {
        "title": "Hardware Architecture & RTL Engineer — AI Core",
        "company": "NVIDIA",
        "location": "Bangalore, India",
        "url": "https://example.com/careers/nvidia-ai-rtl-engineer",
        "description": "Join our deep learning hardware architecture group to implement compute units (MAC arrays, tensor math blocks, RISC-V control logic) and perform cycle-accurate micro-architecture exploration.",
        "required_skills": ["RTL", "Verilog", "AI Hardware", "RISC-V", "Computer Architecture"],
        "date_discovered": "2026-08-16",
        "status": "APPLIED",
        "salary_range": "₹18L - ₹28L PA",
        "experience_level": "0-2 Years",
        "associated_contact_ids": [],
    },
    {
        "title": "Physical Design & Synthesis Engineer",
        "company": "Intel Corporation",
        "location": "Bangalore, India",
        "url": "https://example.com/careers/intel-physical-design",
        "description": "Responsible for RTL-to-GDS implementation, logic synthesis, floorplanning, CTS, and timing closure on cutting-edge process nodes.",
        "required_skills": ["Physical Design", "RTL-to-GDS", "OpenSTA", "Timing Closure", "VLSI"],
        "date_discovered": "2026-08-13",
        "status": "NEW",
        "salary_range": "₹14L - ₹20L PA",
        "experience_level": "1-3 Years",
        "associated_contact_ids": [],
    },
    {
        "title": "RISC-V Core Design Engineer",
        "company": "Western Digital",
        "location": "Bangalore, India",
        "url": "https://example.com/careers/wd-riscv-core-engineer",
        "description": "Design, simulate, and optimize custom open-source SweRV RISC-V pipelined cores for embedded storage silicon controllers.",
        "required_skills": ["RISC-V", "Verilog", "SystemVerilog", "Computer Architecture", "Cache Design"],
        "date_discovered": "2026-08-11",
        "status": "SAVED",
        "salary_range": "₹13L - ₹19L PA",
        "experience_level": "0-2 Years",
        "associated_contact_ids": [],
    },
    {
        "title": "Digital IC Design Engineer (Power & Clock)",
        "company": "Texas Instruments",
        "location": "Bangalore, India",
        "url": "https://example.com/careers/ti-digital-ic-design",
        "description": "Design digital control blocks for precision analog-digital converters and microcontroller power management modules.",
        "required_skills": ["Verilog", "Digital Design", "VLSI", "ASIC", "Simulation"],
        "date_discovered": "2026-08-10",
        "status": "NEW",
        "salary_range": "₹13L - ₹21L PA",
        "experience_level": "0-2 Years",
        "associated_contact_ids": [],
    },
    {
        "title": "EDA Verification Applications Engineer",
        "company": "Synopsys",
        "location": "Noida / Bangalore, India",
        "url": "https://example.com/careers/synopsys-applications-engineer",
        "description": "Collaborate with leading semiconductor tier-1 customers deploying VCS, Verdi, and ZeBu emulation solutions.",
        "required_skills": ["EDA", "SystemVerilog", "Design Verification", "Debugging"],
        "date_discovered": "2026-08-08",
        "status": "NEW",
        "salary_range": "₹12L - ₹18L PA",
        "experience_level": "0-2 Years",
        "associated_contact_ids": [],
    },
    {
        "title": "SoC Interconnect & Fabric RTL Engineer",
        "company": "ARM",
        "location": "Bangalore, India",
        "url": "https://example.com/careers/arm-soc-interconnect",
        "description": "Design and verify high-throughput coherent on-chip interconnect networks, AMBA AXI/CHI protocols, and memory controllers.",
        "required_skills": ["AMBA APB", "SystemVerilog", "SoC", "RTL", "Computer Architecture"],
        "date_discovered": "2026-08-07",
        "status": "NEW",
        "salary_range": "₹16L - ₹25L PA",
        "experience_level": "1-3 Years",
        "associated_contact_ids": [],
    },
]

DEFAULT_OUTREACH_EVENTS = [
    {
        "lead_name": "Demo Contact 12 (Arun C.)",
        "lead_title": "VLSI Digital Design Manager",
        "company": "Texas Instruments",
        "date": "2026-08-16 12:00",
        "status": "INTERVIEW",
        "action_taken": "Interview Scheduled",
        "note": "Technical interview confirmed for upcoming Tuesday covering digital logic design, Verilog coding, and STA.",
        "message_type": "LinkedIn message",
    },
    {
        "lead_name": "Demo Contact 05 (David K.)",
        "lead_title": "Engineering Director — AI Hardware & Architecture",
        "company": "NVIDIA",
        "date": "2026-08-16 11:00",
        "status": "MESSAGE_SENT",
        "action_taken": "Cold Message Sent",
        "note": "Shared breakdown of 64-bit MAC Unit hardware design and pipelined RISC-V core benchmark results.",
        "message_type": "LinkedIn message",
    },
    {
        "lead_name": "Demo Contact 02 (Priya S.)",
        "lead_title": "RTL Lead & Principal Hardware Architect",
        "company": "AMD",
        "date": "2026-08-16 09:30",
        "status": "CONNECTION_SENT",
        "action_taken": "Connection Request Sent",
        "note": "Sent customized connection note referencing AMBA APB protocol verification and OpenLane synthesis.",
        "message_type": "Connection request",
    },
    {
        "lead_name": "Demo Contact 10 (Siddharth P.)",
        "lead_title": "RISC-V Core Micro-Architect & Lead",
        "company": "Western Digital",
        "date": "2026-08-16 06:00",
        "status": "REPLIED",
        "action_taken": "Response Received",
        "note": 'Siddharth replied: "Great work on the 5-stage pipeline with hazard unit. Please share your GitHub repo!"',
        "message_type": "Cold email",
    },
    {
        "lead_name": "Demo Contact 04 (Sneha R.)",
        "lead_title": "Lead Technical Recruiter — Silicon & Hardware",
        "company": "Qualcomm",
        "date": "2026-08-16 07:00",
        "status": "CONNECTED",
        "action_taken": "Connection Accepted",
        "note": "Sneha accepted connection on LinkedIn. Shared profile info for junior DV openings.",
        "message_type": "Connection request",
    },
]
