"""add_daily_lead_batches_and_scoring_fields

Revision ID: bcc80f5d3027
Revises: f6750356da62
Create Date: 2026-09-05 12:08:39.705992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc80f5d3027'
down_revision: Union[str, Sequence[str], None] = 'f6750356da62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_breakdown', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('recommendation_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('technical_areas', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('role_category', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('role_category')
        batch_op.drop_column('technical_areas')
        batch_op.drop_column('recommendation_reason')
        batch_op.drop_column('score_breakdown')

    # ### end Alembic commands ###
