"""add_priority_companies_and_lead_source

Revision ID: ee6a31ef606f
Revises: bcc80f5d3027
Create Date: 2026-09-05 12:54:46.437649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6a31ef606f'
down_revision: Union[str, Sequence[str], None] = 'bcc80f5d3027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    insp = sa.inspect(conn)
    leads_cols = [c['name'] for c in insp.get_columns('leads')]
    settings_cols = [c['name'] for c in insp.get_columns('user_settings')]

    if 'source' not in leads_cols:
        with op.batch_alter_table('leads', schema=None) as batch_op:
            batch_op.add_column(sa.Column('source', sa.String(), nullable=True))

    if 'priority_companies' not in settings_cols:
        with op.batch_alter_table('user_settings', schema=None) as batch_op:
            batch_op.add_column(sa.Column('priority_companies', sa.JSON(), nullable=True, server_default='[]'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('priority_companies')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
